### ISSUE TITLE
Fail to run example

### ISSUE THREAD

**Issue by IvanHristov98** [cloudfoundry/smb-csi-driver#2]
Hi,

We are trying to follow the steps for running the example but we run into the following error:
```bash
MountVolume.SetUp failed for volume "test-smb" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = exit status 1
```

Steps to reproduce (follow the example):
```bash
# This is done on a cluster with a running cf-for-k8s installation
$ kubectl apply --kustomize "https://github.com/cloudfoundry/smb-csi-driver/deploy/overlays/dev/?ref=master" 

# Don't change anything in the `example/pv.yaml`
$ kubectl apply -f ./example/pv.yaml
$ kubectl describe pod nginx
# skipping long logs for readibility
Events:
  Type     Reason            Age                 From                                                  Message
  ----     ------            ----                ----                                                  -------
  Warning  FailedScheduling  <unknown>           default-scheduler                                     pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  Normal   Scheduled         <unknown>           default-scheduler                                     Successfully assigned default/nginx to ip-10-250-13-127.us-east-2.compute.internal
  Warning  FailedMount       100s (x5 over 10m)  kubelet, ip-10-250-13-127.us-east-2.compute.internal  Unable to attach or mount volumes: unmounted volumes=[test-smb], unattached volumes=[test-smb default-token-57pwh]: timed out waiting for the condition
  Warning  FailedMount       29s (x14 over 12m)  kubelet, ip-10-250-13-127.us-east-2.compute.internal  MountVolume.SetUp failed for volume "test-smb" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = exit status 1
```
Possible reasons could be that:
- we aren't changing anything in the `example/pv.yaml`
- we are using `dev` version

What could be causing this?

**Comment by lisamburns** [comment]
Hi @IvanHristov98, thanks for pointing this out.

The example/pv.yaml doesn't work out-of-the-box. It assumes you already have an SMB server deployed somewhere and requires you to edit the pv.yaml to point at the existing SMB server. We could consider including an SMB server deployment as part of the example to make this clearer in the future.

In the meantime if you want to play around with this csi-driver....
You'd need to replace the "username", "password", and "share" fields here:

https://github.com/cloudfoundry/smb-csi-driver/blob/70d345e60142b38d5dc2e0bf3230e3a051369478/example/pv.yaml#L70-L71
https://github.com/cloudfoundry/smb-csi-driver/blob/70d345e60142b38d5dc2e0bf3230e3a051369478/example/pv.yaml#L21

You may also want to change the mount options specified here:
https://github.com/cloudfoundry/smb-csi-driver/blob/70d345e60142b38d5dc2e0bf3230e3a051369478/example/pv.yaml#L13-L15

If you don't have an SMB server handy, samba is relatively easy to get up and running. See
https://github.com/dperson/samba

**Comment by lisamburns** [comment]
Actually we have an example samba deployment you can use in another repo @IvanHristov98 

https://github.com/cloudfoundry/smb-volume-k8s-release/blob/8c13142ba7d5b61d9c5c7f827854a907838724dc/integration-tests/assets/samba.yml

**Comment by IvanHristov98** [comment]
Hi Lisa,

Thanks for the feedback. In such terms I would suggest adding to the tutorial that you need a running samba server (for samba noobs like me :innocent:) and a link with instructions on how to set it up (in the easiest way possible).

I think it would be reasonable to keep the issue open as a reminder until the requested docs are added.

Cheers :beer:

PS - Sorry for the delay.

**Comment by julian-hj** [comment]
@IvanHristov98 I'm going to go ahead and close this as answered, but feel free to re-open it or post new issues if you have further questions. Cheers, -Julian
